# Generated by Django 4.2.6 on 2024-06-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winning_team',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='tournament.team'), on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='tournament.team'),
        ),
    ]
